spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/netbank_read
    user: postgres
    password: postgres
    enabled: true
    locations: classpath:flyway/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/netbank_read
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8082